version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: chatscape-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: chat-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatscape-network

  backend:
    build: ./server
    container_name: chatscape-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/chat-app?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - mongodb
    networks:
      - chatscape-network

  frontend:
    build: ./client
    container_name: chatscape-frontend
    # This container's only job is to build the files and put them in the volume.
    # It doesn't need to run, so no restart policy or ports are needed.
    volumes:
      - frontend_build:/app/dist

  nginx:
    image: nginx:latest
    container_name: chatscape-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      # Mount the nginx config and the built frontend files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - frontend # Ensures frontend is built before Nginx starts
      - backend
    networks:
      - chatscape-network

volumes:
  mongodb_data:
  frontend_build: # The shared volume for the frontend build

networks:
  chatscape-network:
    driver: bridge
