version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: chatscape-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: chat-app
    volumes:
      - mongodb_data:/data/db
    networks:
      - chatscape-network

  backend:
    build: ./server
    container_name: chatscape-backend
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: ${PORT}
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongodb:27017/chat-app?authSource=admin
      JWT_SECRET: ${JWT_SECRET}
      CLOUDINARY_CLOUD_NAME: ${CLOUDINARY_CLOUD_NAME}
      CLOUDINARY_API_KEY: ${CLOUDINARY_API_KEY}
      CLOUDINARY_API_SECRET: ${CLOUDINARY_API_SECRET}
    depends_on:
      - mongodb
    networks:
      - chatscape-network

  frontend:
    build: ./client
    container_name: chatscape-frontend
    restart: unless-stopped
    # No environment variables needed here anymore since we use relative paths
    # No ports needed here, Nginx will handle traffic
    depends_on:
      - backend
    networks:
      - chatscape-network

  nginx:
    image: nginx:latest
    container_name: chatscape-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - chatscape-network

volumes:
  mongodb_data:

networks:
  chatscape-network:
    driver: bridge
